image: timoguehring/droidmateenv:latest

before_script:
  - chmod +x ./gradlew

stages:
  - test

unitTests:
  stage: test
  tags:
        - droidmate
  script:
    - echo "Running unit tests"
    - ./gradlew test