image: timoguehring/droidmatedockerenv:latest

stages:
  - test

unitTestsUnix:
  stage: test
  tags:
        - droidmate
  script:
    - chmod +x ./gradlew
    - echo "Running unit tests on Unix"
    - ./gradlew clean build test --debug

unitTestsWindows:
  stage: test
  tags:
        - droidmatewin
  script:
    - echo "Running unit tests on Windows"
    - ./gradlew clean build test --debug