image: timoguehring/droidmatedockerenv:latest

stages:
  - test

unitTestsUnix:
  stage: test
  tags:
    - droidmate
  script:
    - chmod +x ./gradlew
    - echo "Running unit tests on Unix"
    - ./gradlew clean build test

unitTestsWindows:
  stage: test
  tags:
    - droidmatewin
  script:
    - echo "Running unit tests on Windows"
    - ./gradlew clean build test

job:on-schedule:
  stage: test
  tags:
    - droidmate
  only:
    - schedules
  script:
    - echo "Running scheduled smoke tests on Unix"
    - echo $RESOURCE_REPO
    - echo $TESTING_SET
    - echo $TESTING_DEVICE
    - python ./project/scripts/tester.py $RESOURCE_REPO $TESTING_SET $TESTING_DEVICE
