image: timoguehring/droidmateenv:latest

stages:
  - test

unitTestsUnix:
  stage: test
  tags:
        - droidmate
  script:
    - chmod +x ./gradlew
    - echo "Running unit tests on Unix"
    - ./gradlew test

unitTestsWindows:
  stage: test
  tags:
        - droidmatewin
  script:
    - echo "Running unit tests on Windows"
    - .\gradlew test