language: android
jdk:
  - oraclejdk8
android:
  components:
    # The BuildTools version used by the project
    - build-tools-19.1.0
    # The SDK version used to compile the project
    - android-19
before_install:
# - ls /usr/lib/jvm
 - ls /usr/local
 - chmod +x gradlew
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
 - echo $(where android)
env:
  global:
    - JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - JAVA6_HOME=/usr/lib/jvm/java-6-openjdk-amd64
#    - ANDROID_HOME=$PWD/android-sdk-linux