language: groovy
jdk:
  - oraclejdk8
before_install:
 - chmod +x dev/droidmate/gradlew
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/